baseurl = "https://example.org/"
languageCode = "en-us"
title = "WMA Proposal Review"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Western Museums Association"
	description = "Site for review of submitted 2019 WMA proposals"
	copyright = "2018 Western Museums Association, all rights reserved"

	# Repository

	logo = "images/wmalogo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"
	web 		= ""


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "All Proposals"
	url    = "proposals/"
	weight = 10

[[menu.main]]
	name   = "Proposals by Audience"
	url    = "tags/"
	weight = 20

[[menu.main]]
	name   = "Proposals by Professional Level"
	url    = "categories/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
