baseurl = "/"
languageCode = "en-us"
title = "Western Museums Association Program Committeee"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "assignee"
    weight = 1
    includeNewer = true


[mediaTypes]
  [mediaTypes."application/rtf"]
    suffixes = ["rtf"]

[outputFormats]
	[outputFormats.downloadable]
	  baseName = "proposals"
		isPlainText = true
		mediaType = "application/rtf"
		path = ""

[outputs]
	home = ["HTML", "JSON"]



[params]
	# General information
	author = "Western Museums Association"
	description = "Site for review of submitted 2019 WMA proposals"
	copyright = "2018 Western Museums Association, all rights reserved"

	# Repository

	logo = "images/wmalogo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "westmuse"
	github  = ""
	email   = "programs@westmuse.org"
	web 		= "https://westmuse.org"
	instagram = "https://www.instagram.com/westmuse.pics/"
  facebook = "https://www.facebook.com/westmuse/"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Reviewing Guidelines & Process"
	url    = "pc-materials/"
	weight = 20

[[menu.main]]
	name   = "Timelines & Meeting Agendas"
	url    = "timelines/"
	weight = 25

[[menu.main]]
  name   = "Round 2 Proposals"
  url    = "proposals-round2/"
  weight = 30



[[menu.main]]
	name   = "Round 1 Proposals"
	url    = "proposals/"
	weight = 40

[[menu.main]]
		name   = "Workshop Proposals"
		url    = "workshops/"
		weight = 40
[[menu.main]]
	name   = "Committee Members"
	url    = "pc-members/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
