# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd public/print_output
      - run: ls
      - uses: docker://pandoc/core:2.9
        with:
          args: "public/fuff/proposals.html -f html -t docx -s -o public/print_output/proposals.docx" # gets appended to pandoc command
