# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Change dir
        run: echo "cd public/print_output"
      - name: Pandoc Document Converter
        uses: docker://pandoc/core:2.9
        working-directory: public/print_output
        with:
          args: "proposals.html -f html -t docx -s -o proposals.docx" # gets appended to pandoc command
