# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  compile_latex_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v2
      - run: chmod +x public/print_output/
      - run: git rm public/print_output/print.pdf
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: print.tex  # gets appended to pandoc command
          working_directory: public/print_output/
      - run: git add print.pdf
      - run: git mv print.pdf public/print_output/
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Koven Smith
          author_email: koven@kovenjsmith.com
          message: "Convert HTML proposals list to docx"
          add: "public/print_output/print.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
