# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd public/print_output
      - run: ls
      - run: chmod +x public/print_output/proposals.html
      - uses: docker://pandoc/core:2.9
        with:
          args: "-f html -t docx public/print_output/proposals.html -o proposals.docx" # gets appended to pandoc command
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Koven Smith
          author_email: koven@kovenjsmith.com
          message: "Convert HTML proposals list to docx"
          add: "public/print_output/proposals.docx"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
